const $=id=>document.getElementById(id), screens=[...document.querySelectorAll('.screen')];
let quiz=null,code=location.hash.match(/^#quiz\/([\w-]+)$/)?.[1]||null,current=0,answers=[],selectedMovie=null,draft=[],pending=null,chosen=null,ratingsSelected=false,catalog=[],deck=[],movieIndex=0,regenerationsUsed=0,decoyRequestInFlight=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,options={})=>(await window.firebaseBridgeReady)(path,options);
const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
const text=(selector,value)=>{const el=document.querySelector(selector);if(el)el.textContent=value};
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));$('quizSticky').style.display=id==='quiz'?'block':'none';window.scrollTo(0,0);if(id==='login')prefillNickname()}
function toast(message){const el=$('toast');el.textContent=message;el.style.opacity=1;setTimeout(()=>el.style.opacity=0,3000)}
function updateAuthUI(state){document.querySelectorAll('.googleAuthStatus').forEach(el=>{el.textContent=state?.isGoogle?`${state.email} 계정으로 로그인했습니다.${state.pendingMerge?' 이전 게스트 문제 연결을 다시 시도해 주세요.':''}`:state?.pendingMerge?'기존 Google 계정이 있습니다. 아래 버튼을 다시 눌러 게스트 문제를 연결하세요.':'게스트로 이용 중이에요. Google 계정을 연결하면 다른 기기에서도 내 문제를 볼 수 있어요.'});document.querySelectorAll('.googleAuthButton').forEach(btn=>{btn.hidden=!!state?.isGoogle&&!state?.pendingMerge;btn.textContent=state?.pendingMerge?(state.isGoogle?'기존 문제 연결 다시 시도':'Google 계정으로 이어서 로그인'):'Google 계정 연결하기'});document.querySelectorAll('.googleSignOutButton').forEach(btn=>btn.hidden=!state?.isGoogle||!!state?.pendingMerge)}
let nicknameAccount='',nicknameRequest=0,autoFilledNickname='';
async function prefillNickname(){
 const state=window.getGuessmindAuthState?.();
 if(!state?.isGoogle)return;
 const account=state.email,request=++nicknameRequest,previous=$('nickname').value;
 try{
  const {nickname}=await api('/profile');
  if(request!==nicknameRequest||window.getGuessmindAuthState?.().email!==account)return;
  if(nickname&&$('nickname').value===previous){$('nickname').value=nickname;autoFilledNickname=nickname}
 }catch(e){console.error('닉네임 불러오기 실패',e)}
}
window.onGuessmindAuthChanged=state=>{
 updateAuthUI(state);
 if(state?.isGoogle){if(nicknameAccount!==state.email){if(nicknameAccount)$('nickname').value='';nicknameAccount=state.email}prefillNickname()}
 else if(nicknameAccount){nicknameAccount='';nicknameRequest++;if($('nickname').value===autoFilledNickname)$('nickname').value='';autoFilledNickname=''}
};
async function connectGoogle(btn){if(!window.googleSignIn){toast('로그인을 준비하는 중입니다. 잠시 후 다시 시도해 주세요.');return}btn.disabled=true;btn.textContent='Google 로그인 창을 여는 중…';try{const result=await window.googleSignIn();if(result.needsExisting){toast('이미 사용 중인 Google 계정입니다. 버튼을 한 번 더 눌러 문제를 연결해 주세요.')}else{toast(result.migrated?`Google 로그인 완료 · 기존 문제 ${result.migrated}개 연결`:'Google 계정이 연결됐습니다.');await prefillNickname();if(document.getElementById('myQuizzes').classList.contains('active'))await openMyQuizzes()}}catch(e){if(e.code==='auth/popup-closed-by-user'||e.code==='auth/cancelled-popup-request')return;toast(e.code==='auth/unauthorized-domain'?'Firebase 승인된 도메인에 guessmind.eunlab.com을 추가해 주세요.':e.code==='auth/operation-not-allowed'?'Firebase에서 Google 로그인 제공업체를 활성화해 주세요.':e.code==='auth/popup-blocked'?'팝업 차단을 해제하고 다시 시도해 주세요.':e.message||'Google 로그인에 실패했습니다.')}finally{btn.disabled=false;updateAuthUI(window.getGuessmindAuthState?.())}}
async function disconnectGoogle(){try{await window.googleSignOut();toast('로그아웃했습니다. 다시 로그인하면 내 문제를 볼 수 있어요.');if(document.getElementById('myQuizzes').classList.contains('active'))await openMyQuizzes()}catch(e){toast(e.message)}}
function applyOwner(name){document.querySelectorAll('[data-copy]').forEach(el=>{const template=window.PROTOTYPE_COPY[el.dataset.copy];if(template)el.innerHTML=template.replaceAll('{닉네임}',esc(name))});document.querySelector('.avatar').textContent=name.slice(0,1)}
function makeStarRating(id,initial,onChange){const root=$(id);root.innerHTML=`<div class="star-buttons" role="radiogroup" aria-label="0점부터 10점까지 반개 별점"><button type="button" class="zero-score" data-score="0">0점</button>${Array.from({length:10},(_,i)=>`<button type="button" class="star-half ${i%2?'right':'left'}" data-score="${i+1}" aria-label="${i+1}점"><span>★</span></button>`).join('')}</div><output class="score-label"></output>`;const paint=score=>{root.dataset.value=score;root.querySelectorAll('.star-half').forEach(b=>b.classList.toggle('filled',Number(b.dataset.score)<=score));root.querySelector('output').textContent=`${Number(score).toFixed(1)} / 10`};root.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{paint(Number(b.dataset.score));onChange?.(Number(b.dataset.score))});paint(initial)}
async function loadQuiz(){if(!code){applyOwner(window.PROTOTYPE_COPY.nickname);show('login');return}try{quiz=await api('/quizzes/'+encodeURIComponent(code));applyOwner(quiz.owner);document.querySelector('.stats .stat b').textContent=quiz.questions.length+'문제';show('home');ensureShareButton()}catch(e){toast(e.message);show('login')}}
async function startChallenge(){const nickname=$('challengerNickname').value.trim();try{if(nickname.length<2||nickname.length>12)throw Error('닉네임은 2~12자로 입력해주세요.');await post('/session',{nickname});startQuiz()}catch(e){toast(e.message)}}
function ensureShareButton(){const actions=document.querySelector('#home .actions');if(!document.getElementById('shareQuizButton')){const b=document.createElement('button');b.id='shareQuizButton';b.className='kakao';b.textContent='카카오톡으로 퀴즈 공유';b.onclick=()=>shareQuiz();actions.prepend(b)}}
async function openMyQuizzes(){show('myQuizzes');const list=$('myQuizList');list.innerHTML='<p class="list-empty">내 문제를 불러오는 중이에요.</p>';try{const {quizzes}=await api('/my-quizzes');if(!quizzes.length){list.innerHTML='<p class="list-empty">아직 만든 문제가 없어요.<br>영화 세 편으로 첫 퀴즈를 만들어보세요.</p>';return}list.replaceChildren(...quizzes.map(item=>{const card=document.createElement('article');card.className='owned-card';const date=item.createdAt?new Date(item.createdAt).toLocaleDateString('ko-KR'):'';card.innerHTML=`<h2>${esc(item.movies.join(' · '))}</h2><p>${esc(item.owner)}님 · ${esc(date)}</p><div class="row"><button type="button" class="primary">결과 보기</button><button type="button" class="secondary">퀴즈 보기</button><button type="button" class="secondary">링크 공유</button></div>`;card.querySelector('.primary').onclick=()=>openOwnerResults(item.code);card.querySelectorAll('.secondary')[0].onclick=()=>openOwnedQuiz(item.code);card.querySelectorAll('.secondary')[1].onclick=()=>shareOwnedQuiz(item.code);return card}))}catch(e){list.innerHTML='<p class="list-empty">목록을 불러오지 못했어요. 다시 시도해 주세요.</p>';toast(e.message)}}
async function openOwnerResults(ownedCode){
 show('ownerResults');
 $('ownerResultSubtitle').textContent='결과를 불러오는 중이에요.';
 $('ownerAnswers').replaceChildren();
 $('ownerAttempts').replaceChildren();
 try{
  const data=await post('/owner-result',{code:ownedCode});
  if(!document.getElementById('ownerResults').classList.contains('active'))return;
  $('ownerResultSubtitle').textContent=`${data.owner}님의 영화 취향 퀴즈 · 참여 ${data.attempts.length}명${data.attempts.length===100?' (최근 조회 범위 최대 100명)':''}`;
  $('ownerAnswers').innerHTML=data.questions.map((q,i)=>`<article class="owner-question"><h3>${i+1}. ${esc(q.movie.title)}</h3><p><b>정답 평점</b> ${Number(q.rating).toFixed(1)}점 / 10점</p><p><b>진짜 한줄평</b> ${esc(q.review)}</p><p class="muted">오답 보기</p><ul>${q.decoys.map(d=>`<li>${esc(d)}</li>`).join('')}</ul></article>`).join('');
  $('ownerAttempts').innerHTML=data.attempts.length?data.attempts.map((a,i)=>`<details class="owner-attempt"><summary><span><b>${i+1}위 · ${esc(a.nickname)}</b><br><small>${a.createdAt?esc(new Date(a.createdAt).toLocaleString('ko-KR')):''}</small></span><strong>${a.score}점 · ${esc(a.title)}</strong></summary><div class="breakdown">${a.details?a.details.map((d,j)=>`<p><b>${esc(data.questions[j]?.movie.title||'영화')}</b><br>선택한 평점 ${Number(d.rating).toFixed(1)}점 · ${d.ratingPoints}점 획득<br>선택한 한줄평: <span class="${d.reviewPoints?'correct':'incorrect'}">${esc(d.review)}</span> · ${d.reviewPoints}점 획득</p>`).join(''):'이전 참여 기록은 총점만 저장되어 문항별 선택을 확인할 수 없어요.'}</div></details>`).join(''):'<p class="list-empty">아직 참여한 도전자가 없어요.</p>';
 }catch(e){$('ownerResultSubtitle').textContent='결과를 불러오지 못했어요.';$('ownerAnswers').innerHTML='<p class="list-empty">잠시 후 다시 시도해 주세요.</p>';toast(e.message)}
}
async function openOwnedQuiz(ownedCode){code=ownedCode;history.replaceState(null,'','#quiz/'+code);await loadQuiz()}
async function shareOwnedQuiz(ownedCode){const url=location.origin+location.pathname+'#quiz/'+ownedCode;if(navigator.share){try{await navigator.share({title:'게스마인드 영화 취향 퀴즈',url});return}catch{}}try{await navigator.clipboard.writeText(url);toast('퀴즈 링크를 복사했습니다.')}catch{toast('링크를 복사할 수 없습니다. 퀴즈 보기에서 주소를 복사해 주세요.')}}
function startQuiz(){if(!quiz){toast('공유받은 퀴즈 링크로 접속해주세요.');return}answers=[];current=0;renderQuiz();show('quiz')}
function renderQuiz(){const q=quiz.questions[current],m=q.movie;$('qnum').textContent=current+1;$('movieTitle').textContent=m.title;$('movieMeta').textContent=[m.year,m.original_title].filter(Boolean).join(' · ');const poster=$('posterText');poster.textContent=m.title;$('choices').replaceChildren(...q.choices.map((choice,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${'ABCDE'[i]}</b>${esc(choice.text)}`;b.onclick=()=>{chosen=choice.id;$('choices').querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');ready()};return b}));chosen=null;ratingsSelected=false;makeStarRating('ratings',0,()=>{ratingsSelected=true;ready()});$('p2').classList.toggle('on',current>0);$('p3').classList.toggle('on',current>1);ready()}
function ready(){const b=$('nextBtn');b.disabled=!(ratingsSelected&&chosen);b.style.opacity=b.disabled?'.45':'1';b.textContent=current===2?'결과 확인':'다음 문제'}
async function nextQuestion(){if(!ratingsSelected||!chosen)return;answers.push({rating:Number($('ratings').dataset.value),choiceId:chosen});if(current<quiz.questions.length-1){current++;renderQuiz();window.scrollTo(0,0);return}try{const result=await post('/quizzes/'+code+'/attempts',{answers});renderResult(result);show('result')}catch(e){toast(e.message);if(e.message.includes('이미 참여'))show('home')}}
function renderResult(data){text('.score-inner b',data.score);text('.badge',data.title);text('.result-card p',`${quiz.owner}님의 취향 이해도 ${data.score}점`);text('.rank-score',data.score+'점');$('rankingRows').innerHTML=data.ranking.map((r,i)=>`<div class="rank-row"><span class="rank-no">${i+1}</span><span class="rank-avatar">${esc(r.nickname.slice(0,1))}</span><strong>${esc(r.nickname)}</strong><span class="rank-score">${r.score}점</span></div>`).join('');$('answerList').innerHTML=data.details.map((d,i)=>`<div class="answer"><strong>${esc(quiz.questions[i].movie.title)}</strong><span class="${d.reviewPoints?'ok':'no'}">평점 ${d.ratingPoints} · 한줄평 ${d.reviewPoints}</span></div>`).join('');window.resultShare={score:data.score,title:data.title}}
async function startAsGuest(){const nickname=$('nickname').value.trim();try{if(nickname.length<2||nickname.length>12)throw Error('닉네임은 2~12자로 입력해주세요.');await post('/session',{nickname});draft=[];newQuestion()}catch(e){toast(e.message)}}
async function ensureCatalog(){if(catalog.length)return;const data=await api('/movies');catalog=data.movies}
function refillDeck(){deck=catalog.filter(m=>!draft.some(q=>q.movie.id===m.id)).sort(()=>Math.random()-.5);movieIndex=0}
function renderPicker(){if(movieIndex>=deck.length)deck.push(...catalog.filter(m=>!draft.some(q=>q.movie.id===m.id)).sort(()=>Math.random()-.5));const m=deck[movieIndex];$('moviePicker').innerHTML=`<div class="picker-card"><span class="picker-kicker">영화 카드</span><h2>${esc(m.title)}</h2><p>이 영화에 남길 평점과 한줄평이 있나요?</p></div>`;$('pickerCount').textContent=`${movieIndex+1}번째 카드 · ${catalog.length}편 중에서 고르기`;$('previousMovieButton').disabled=movieIndex===0}
function skipMovie(){movieIndex++;renderPicker()}
function previousMovie(){if(movieIndex===0)return;movieIndex--;renderPicker()}
function selectMovie(){selectedMovie=deck[movieIndex];$('selectedMovieLabel').textContent=`선택한 영화 · ${selectedMovie.title}`;$('moviePicker').hidden=true;document.querySelector('.picker-actions').hidden=true;$('pickerCount').hidden=true;document.querySelector('#create .form-label').scrollIntoView({behavior:'smooth',block:'center'})}
async function newQuestion(){try{await ensureCatalog();selectedMovie=null;pending=null;regenerationsUsed=0;refillDeck();$('review').value='';$('selectedMovieLabel').textContent='';$('moviePicker').hidden=false;document.querySelector('.picker-actions').hidden=false;$('pickerCount').hidden=false;makeStarRating('createRatings',0);document.querySelector('#create .eyebrow').textContent=`${['첫 번째','두 번째','세 번째'][draft.length]} 문제 · ${draft.length+1}/3`;renderPicker();show('create')}catch(e){toast(e.message)}}
function updateRegenerationButton(){const button=$('regenerateDecoys');if(!button)return;const remaining=3-regenerationsUsed;button.disabled=decoyRequestInFlight||remaining===0;button.textContent=remaining?`오답 다시 만들기 · ${remaining}회 남음`:'재생성 횟수를 모두 사용했어요'}
async function generateAI(btn){if(decoyRequestInFlight)return;const isRetry=!!pending;if(isRetry&&regenerationsUsed>=3){toast('이 문제의 오답은 세 번까지 다시 만들 수 있어요.');return}if(!selectedMovie){toast('영화 카드를 선택해주세요.');return}const review=isRetry?pending.review:$('review').value.trim(),rating=isRetry?pending.rating:Number($('createRatings').dataset.value);if(!review||review.length>80){toast('한줄평을 1~80자로 입력해주세요.');return}decoyRequestInFlight=true;btn.disabled=true;const originalText=btn.textContent,saveButton=$('saveQuestionButton'),status=isRetry?$('decoyGenerationStatus'):$('createGenerationStatus');if(saveButton&&isRetry)saveButton.disabled=true;status.hidden=false;status.textContent=isRetry?'새 오답을 만드는 중이에요. 잠시만 기다려주세요.':'오답 네 개를 만드는 중이에요. 잠시만 기다려주세요.';btn.classList.add('is-loading');btn.setAttribute('aria-busy','true');btn.innerHTML='<span class="loading-spinner" aria-hidden="true"></span><span>'+(isRetry?'오답 다시 만드는 중…':'오답 만드는 중…')+'</span>';try{const result=await post('/decoys',{title:selectedMovie.title,review});pending={movie:selectedMovie,rating,review,decoys:result.decoys};if(isRetry)regenerationsUsed++;renderDecoys();show('decoys')}catch(e){toast(e.message)}finally{decoyRequestInFlight=false;btn.classList.remove('is-loading');btn.removeAttribute('aria-busy');btn.textContent=originalText;btn.disabled=false;if(saveButton)saveButton.disabled=false;if(status){status.hidden=true;status.textContent=''}updateRegenerationButton()}}
function renderDecoys(){updateRegenerationButton();$('decoyChoices').innerHTML=`<div class="choice selected"><b>진짜</b>${esc(pending.review)}</div>`+pending.decoys.map((d,i)=>`<label class="choice"><b>AI</b><input data-decoy="${i}" value="${esc(d)}" maxlength="80" class="field" aria-label="오답 ${i+1} 수정"></label>`).join('')}
async function saveQuestion(){if(decoyRequestInFlight)return;const decoys=[...document.querySelectorAll('[data-decoy]')].map(x=>x.value.trim());if(decoys.some(x=>!x||x===pending.review)||new Set(decoys).size!==4){toast('서로 다른 오답 네 개를 입력해주세요.');return}draft.push({...pending,decoys});if(draft.length<3){toast('문제를 저장했습니다. 다음 영화를 골라주세요.');newQuestion();return}try{const saved=await post('/quizzes',{questions:draft});code=saved.code;history.replaceState(null,'','#quiz/'+code);await loadQuiz();toast('퀴즈가 완성됐어요. 공유 링크를 보내보세요.');ensureShareButton()}catch(e){draft.pop();toast(e.message)}}
async function share(type){const url=location.origin+location.pathname+'#quiz/'+code, config=await api('/config');const title=type==='result'?`게스마인드 ${window.resultShare?.score}점 · ${window.resultShare?.title}`:`${quiz.owner}님의 영화 취향 퀴즈`;if(config.kakaoKey){try{if(!window.Kakao){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://t1.kakaocdn.net/kakao_js_sdk/2.7.4/kakao.min.js';s.onload=ok;s.onerror=no;document.head.append(s)})}if(!Kakao.isInitialized())Kakao.init(config.kakaoKey);Kakao.Share.sendDefault({objectType:'feed',content:{title,description:type==='result'?'당신도 영화 취향을 맞혀보세요.':'별점과 진짜 한줄평을 맞혀보세요.',imageUrl:`${location.origin}/share.svg`,link:{mobileWebUrl:url,webUrl:url}},buttons:[{title:'퀴즈 풀기',link:{mobileWebUrl:url,webUrl:url}}]});return}catch(e){console.error(e);toast('카카오 공유 설정을 확인해주세요. 링크를 복사합니다.')}}if(navigator.share){try{await navigator.share({title,url});return}catch{}}await navigator.clipboard.writeText(url);toast('퀴즈 링크를 복사했습니다.')}
function shareQuiz(){share('quiz').catch(e=>toast(e.message))}function shareResult(){share('result').catch(e=>toast(e.message))}
makeStarRating('createRatings',0);updateAuthUI(window.getGuessmindAuthState?.());loadQuiz();
