const $=id=>document.getElementById(id), screens=[...document.querySelectorAll('.screen')];
let quiz=null,code=location.hash.match(/^#quiz\/([\w-]+)$/)?.[1]||null,current=0,answers=[],selectedMovie=null,draft=[],pending=null,chosen=null,ratingsSelected=false,catalog=[],deck=[],movieIndex=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,options={})=>(await window.firebaseBridgeReady)(path,options);
const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
const text=(selector,value)=>{const el=document.querySelector(selector);if(el)el.textContent=value};
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));$('quizSticky').style.display=id==='quiz'?'block':'none';window.scrollTo(0,0)}
function toast(message){const el=$('toast');el.textContent=message;el.style.opacity=1;setTimeout(()=>el.style.opacity=0,3000)}
function applyOwner(name){document.querySelectorAll('[data-copy]').forEach(el=>{const template=window.PROTOTYPE_COPY[el.dataset.copy];if(template)el.innerHTML=template.replaceAll('{닉네임}',esc(name))});document.querySelector('.avatar').textContent=name.slice(0,1)}
function makeStarRating(id,initial,onChange){const root=$(id);root.innerHTML=`<div class="star-buttons" role="radiogroup" aria-label="0점부터 10점까지 반개 별점"><button type="button" class="zero-score" data-score="0">0점</button>${Array.from({length:10},(_,i)=>`<button type="button" class="star-half ${i%2?'right':'left'}" data-score="${i+1}" aria-label="${i+1}점"><span>★</span></button>`).join('')}</div><output class="score-label"></output>`;const paint=score=>{root.dataset.value=score;root.querySelectorAll('.star-half').forEach(b=>b.classList.toggle('filled',Number(b.dataset.score)<=score));root.querySelector('output').textContent=`${Number(score).toFixed(1)} / 10`};root.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{paint(Number(b.dataset.score));onChange?.(Number(b.dataset.score))});paint(initial)}
async function loadQuiz(){if(!code){applyOwner(window.PROTOTYPE_COPY.nickname);show('login');return}try{quiz=await api('/quizzes/'+encodeURIComponent(code));applyOwner(quiz.owner);document.querySelector('.stats .stat b').textContent=quiz.questions.length+'문제';show('home');ensureShareButton()}catch(e){toast(e.message);show('login')}}
async function startChallenge(){const nickname=$('challengerNickname').value.trim();try{if(nickname.length<2||nickname.length>12)throw Error('닉네임은 2~12자로 입력해주세요.');await post('/session',{nickname});startQuiz()}catch(e){toast(e.message)}}
function ensureShareButton(){const actions=document.querySelector('#home .actions');if(!document.getElementById('shareQuizButton')){const b=document.createElement('button');b.id='shareQuizButton';b.className='kakao';b.textContent='카카오톡으로 퀴즈 공유';b.onclick=()=>shareQuiz();actions.prepend(b)}}
function startQuiz(){if(!quiz){toast('공유받은 퀴즈 링크로 접속해주세요.');return}answers=[];current=0;renderQuiz();show('quiz')}
function renderQuiz(){const q=quiz.questions[current],m=q.movie;$('qnum').textContent=current+1;$('movieTitle').textContent=m.title;$('movieMeta').textContent=[m.year,m.original_title].filter(Boolean).join(' · ');const poster=$('posterText');poster.textContent=m.title;$('choices').replaceChildren(...q.choices.map((choice,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${'ABCDE'[i]}</b>${esc(choice.text)}`;b.onclick=()=>{chosen=choice.id;$('choices').querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');ready()};return b}));chosen=null;ratingsSelected=false,catalog=[],deck=[],movieIndex=0;makeStarRating('ratings',0,()=>{ratingsSelected=true;ready()});$('p2').classList.toggle('on',current>0);$('p3').classList.toggle('on',current>1);ready()}
function ready(){const b=$('nextBtn');b.disabled=!(ratingsSelected&&chosen);b.style.opacity=b.disabled?'.45':'1';b.textContent=current===2?'결과 확인':'다음 문제'}
async function nextQuestion(){if(!ratingsSelected||!chosen)return;answers.push({rating:Number($('ratings').dataset.value),choiceId:chosen});if(current<quiz.questions.length-1){current++;renderQuiz();window.scrollTo(0,0);return}try{const result=await post('/quizzes/'+code+'/attempts',{answers});renderResult(result);show('result')}catch(e){toast(e.message);if(e.message.includes('이미 참여'))show('home')}}
function renderResult(data){text('.score-inner b',data.score);text('.badge',data.title);text('.result-card p',`${quiz.owner}님의 취향 이해도 ${data.score}점`);text('.rank-score',data.score+'점');$('rankingRows').innerHTML=data.ranking.map((r,i)=>`<div class="rank-row"><span class="rank-no">${i+1}</span><span class="rank-avatar">${esc(r.nickname.slice(0,1))}</span><strong>${esc(r.nickname)}</strong><span class="rank-score">${r.score}점</span></div>`).join('');$('answerList').innerHTML=data.details.map((d,i)=>`<div class="answer"><strong>${esc(quiz.questions[i].movie.title)}</strong><span class="${d.reviewPoints?'ok':'no'}">평점 ${d.ratingPoints} · 한줄평 ${d.reviewPoints}</span></div>`).join('');window.resultShare={score:data.score,title:data.title}}
async function startAsGuest(){const nickname=$('nickname').value.trim();try{if(nickname.length<2||nickname.length>12)throw Error('닉네임은 2~12자로 입력해주세요.');await post('/session',{nickname});draft=[];newQuestion()}catch(e){toast(e.message)}}
async function ensureCatalog(){if(catalog.length)return;const data=await api('/movies');catalog=data.movies}
function refillDeck(){deck=catalog.filter(m=>!draft.some(q=>q.movie.id===m.id)).sort(()=>Math.random()-.5);movieIndex=0}
function renderPicker(){if(movieIndex>=deck.length)refillDeck();const m=deck[movieIndex];$('moviePicker').innerHTML=`<div class="picker-card"><span class="picker-kicker">영화 카드</span><h2>${esc(m.title)}</h2><p>이 영화에 남길 평점과 한줄평이 있나요?</p></div>`;$('pickerCount').textContent=`${movieIndex+1} / ${deck.length}편 · 언제든 넘길 수 있어요`}
function skipMovie(){movieIndex++;renderPicker()}
function selectMovie(){selectedMovie=deck[movieIndex];$('selectedMovieLabel').textContent=`선택한 영화 · ${selectedMovie.title}`;$('moviePicker').hidden=true;document.querySelector('.picker-actions').hidden=true;$('pickerCount').hidden=true;document.querySelector('#create .form-label').scrollIntoView({behavior:'smooth',block:'center'})}
async function newQuestion(){try{await ensureCatalog();selectedMovie=null;pending=null;refillDeck();$('review').value='';$('selectedMovieLabel').textContent='';$('moviePicker').hidden=false;document.querySelector('.picker-actions').hidden=false;$('pickerCount').hidden=false;makeStarRating('createRatings',0);document.querySelector('#create .eyebrow').textContent=`${['첫 번째','두 번째','세 번째'][draft.length]} 문제 · ${draft.length+1}/3`;renderPicker();show('create')}catch(e){toast(e.message)}}
async function generateAI(btn){if(!selectedMovie){toast('영화 카드를 선택해주세요.');return}const review=$('review').value.trim(),rating=Number($('createRatings').dataset.value);if(!review||review.length>80){toast('한줄평을 1~80자로 입력해주세요.');return}btn.disabled=true;try{const result=await post('/decoys',{title:selectedMovie.title,review});pending={movie:selectedMovie,rating,review,decoys:result.decoys};renderDecoys();show('decoys')}catch(e){toast(e.message)}finally{btn.disabled=false}}
function renderDecoys(){$('decoyChoices').innerHTML=`<div class="choice selected"><b>진짜</b>${esc(pending.review)}</div>`+pending.decoys.map((d,i)=>`<label class="choice"><b>AI</b><input data-decoy="${i}" value="${esc(d)}" maxlength="80" class="field" aria-label="오답 ${i+1} 수정"></label>`).join('')}
async function saveQuestion(){const decoys=[...document.querySelectorAll('[data-decoy]')].map(x=>x.value.trim());if(decoys.some(x=>!x||x===pending.review)||new Set(decoys).size!==4){toast('서로 다른 오답 네 개를 입력해주세요.');return}draft.push({...pending,decoys});if(draft.length<3){toast('문제를 저장했습니다. 다음 영화를 골라주세요.');newQuestion();return}try{const saved=await post('/quizzes',{questions:draft});code=saved.code;history.replaceState(null,'','#quiz/'+code);await loadQuiz();toast('퀴즈가 완성됐어요. 공유 링크를 보내보세요.');ensureShareButton()}catch(e){draft.pop();toast(e.message)}}
async function share(type){const url=location.origin+location.pathname+'#quiz/'+code, config=await api('/config');const title=type==='result'?`게스마인드 ${window.resultShare?.score}점 · ${window.resultShare?.title}`:`${quiz.owner}님의 영화 취향 퀴즈`;if(config.kakaoKey){try{if(!window.Kakao){await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://t1.kakaocdn.net/kakao_js_sdk/2.7.4/kakao.min.js';s.onload=ok;s.onerror=no;document.head.append(s)})}if(!Kakao.isInitialized())Kakao.init(config.kakaoKey);Kakao.Share.sendDefault({objectType:'feed',content:{title,description:type==='result'?'당신도 영화 취향을 맞혀보세요.':'별점과 진짜 한줄평을 맞혀보세요.',imageUrl:`${location.origin}/share.svg`,link:{mobileWebUrl:url,webUrl:url}},buttons:[{title:'퀴즈 풀기',link:{mobileWebUrl:url,webUrl:url}}]});return}catch(e){console.error(e);toast('카카오 공유 설정을 확인해주세요. 링크를 복사합니다.')}}if(navigator.share){try{await navigator.share({title,url});return}catch{}}await navigator.clipboard.writeText(url);toast('퀴즈 링크를 복사했습니다.')}
function shareQuiz(){share('quiz').catch(e=>toast(e.message))}function shareResult(){share('result').catch(e=>toast(e.message))}
makeStarRating('createRatings',0);loadQuiz();
